export const HOME_CASUAL = 'home_casual';//首页轮播图
export const HOME_NAV = 'home_nav'; //首页导航
export const HOME_SHOP_LIST = 'home_shop_list';//首页商品列表
export const REC_SHOP_LIST = 'rec_shop_list';//获取推荐列表
export const SEARCH_LIST = 'search_list';//搜索商品信息
export const SYNC_USER_INFO = 'sync_user_info';//同步用户信息
export const CLEAN_USER_INFO ='clean_user_info';//清空用户信息
export const ADD_GOODS_COUNT = 'add_goods_count'; //增加购物车商品的数量
export const REDUCE_GOODS_COUNT = 'reduce_goods_count'; //减少购物车商品的数量
export const SINGER_GOODS_SELECT = 'singer_goods_select'; //单个商品的选中和取消选中
export const ALL_GOODS_SELECT = 'all_goods_select' ; //购物车商品全部选中和取消全选
export const DEL_GOODS_SINGER = 'del_goods_singer' ; //删除购物车中单个商品
